server:
  port: 8084
Spring:
  application:
    name: API-GATEWAY


    yaml:cloud:
    gateway:
      routes:
        - id: USER_SERVICE
          uri: lb://USER_SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL_SERVICE
          uri: lb://HOTEL_SERVICE
          predicates:
            - Path=/hotels/**


        - id: RATING_SERVICE
          uri: lb://RATING_SERVICE
          predicates:
            - Path=/ratings/**




eureka:
  instance:
    prefer-ip-address: true
client:
  fetch-registry: true
  register-with-eureka: true
  server url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/
