server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    username: root
    password: sameena
    driver-class-name: com.mysql.cj.jdbc.Driver




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: USER_SERVICE


eureka:
  instance:
    prefer-ip-address: true
client:
  fetch-registry: true
  register-with-eureka: true
  server url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/
